### ISSUE TITLE
staticPath: path.join(__dirname, 'public')报错

### ISSUE THREAD

**Issue by Chanran** [longmenwaideyu/ueditor-nodejs#4]
报错信息:path is not defined
`app.use('/ueditor/ue',ueditor({//这里的/ueditor/ue是因为文件重命名为了ueditor,如果没改名，那么应该是/ueditor版本号/ue
    configFile: '/ueditor/php/config.json',//如果下载的是jsp的，就填写/ueditor/jsp/config.json
    mode: 'bcs', //本地存储填写local
    accessKey: 'Adxxxxxxx',//本地存储不填写，bcs填写
    secrectKey: 'oiUqt1VpH3fdxxxx',//本地存储不填写，bcs填写
    staticPath: path.join(__dirname, 'public'), //一般固定的写法，静态资源的目录，如果是bcs，可以不填
    dynamicPath: '/blogpicture' //动态目录，以/开头，bcs填写buckect名字，开头没有/.路径可以根据req动态变化，可以是一个函数，function(req) { return '/xx'} req.query.action是请求的行为，uploadimage表示上传图片，具体查看config.json.
}));`

初学Nodejs要使用ueditor,求指教

**Comment by longmenwaideyu** [comment]
path是nodejs的一个模块，你需要先require。如下
var path = require('path');

**Comment by Chanran** [comment]
啊!谢谢啊,我之前不会node,现在有点懂了,那个问题已经解决了.谢谢
